export const PATHS = {
	BASE_URL: '',
	ADMIN: 'admin',
	ADMIN_CONFIG: 'admin-config',
	ADMIN_NIVELATION: 'admin-nivelation',
	ADMIN_USERS_LIST: 'admin-users-list',
	ADMIN_USER_INFO: 'admin-user-info',
	ADMIN_TAGS: 'admin-tags',
	ADMIN_EXERCISES: 'admin-exercises',
	ADMIN_LEVELS: 'admin-levels',
	ADMIN_TRAINING: 'admin-training',
	ADMIN_TRAINING_LEVEL: 'admin-trainings/:level',
	ADMIN_CREATE_EDIT_EXERCISE: 'admin-create-edit-exercise',

	CHANGE_USER_PASSWORD: 'change-user-password',
	LOGIN: 'login',
	PASSWORD_RECOVERY: 'password-recovery',
	FORGOTTEN_PASSWORD: 'forgotten-password',
	VERIFY_EMAIL: 'verify-email',
	ENABLED_VERIFIED: 'enabled-verified',
	REGISTER: 'register',
	MY_PROFILE: 'my-profile',
	HELP: 'help',
	WELCOME: 'welcome',
	EMAIL_REGISTER_SENDED: 'email-register-sended',
	MAIN_GOALS: 'main-goals',
	TRAINING_LEVEL: 'training-level',
	WEIGHT_HEIGHT: 'weight-height',
	CONTACT: 'contact',
	DASHBOARD: 'dashboard',
	MY_PROGRESS: 'dashboard/my-progress',
	NIVELATION: 'nivelation',
	NIVELATION_EXERCISE: 'nivelation-exercise',
	TRAINING: 'training-dashboard',
	EDIT_PROFILE: 'edit-profile',
	EDIT_ABOUT_YOU: 'edit-about-you',
	TRAINING_ROUTINE: 'training-routine',
	TRAINING_DASHBOARD: 'training-dashboard',
	MAKE_TRAINING: 'make-training',
	CONGRATULATIONS: 'congratulations',
	FEEDBACK: 'feedback',
};

export const SHOW_NAVBAR = [PATHS.BASE_URL];

export const TOPBAR_TEXTS = {
	[PATHS.BASE_URL]: 'topBar.main',
	[PATHS.ADMIN_USERS_LIST]: 'topBar.usersList',
	[PATHS.CHANGE_USER_PASSWORD]: 'topBar.changeUserPassword',
	[PATHS.LOGIN]: 'topBar.login',
	[PATHS.PASSWORD_RECOVERY]: 'topBar.passwordRecovery',
	[PATHS.FORGOTTEN_PASSWORD]: 'topBar.forgottenPassword',
	[PATHS.VERIFY_EMAIL]: 'topBar.verifyEmail',
	[PATHS.ENABLED_VERIFIED]: 'topBar.enabledVerified',
	[PATHS.REGISTER]: 'topBar.register',
	[PATHS.MY_PROFILE]: 'topBar.myProfile',
	[PATHS.EMAIL_REGISTER_SENDED]: 'topBar.emailRegisterSended',
	[PATHS.HELP]: 'topBar.help',
	[PATHS.EMAIL_REGISTER_SENDED]: 'topBar.emailRegisterSended',
	[PATHS.CONTACT]: 'topBar.contact',
	[PATHS.DASHBOARD]: 'topBar.dashboard',
	[PATHS.EDIT_PROFILE]: 'topBar.editProfile',
	[PATHS.EDIT_ABOUT_YOU]: 'topBar.editAboutYou'
};
